### ISSUE TITLE
tunneling a port by using websocket/http

### ISSUE THREAD

**Issue by mokhtarabadi** [ninetymiles/wsl-socks#13]
can u use this library to forward any TCP data instead of the only socks5?

**Comment by ninetymiles** [comment]
Thanks for your feedback.

Currently no plan to add raw socket tunnel supports, if you need such behavior, u can try shadowsocks, shadowsocksR, v2fly or trojan.

**Comment by mokhtarabadi** [comment]
thanks for your great project.
I searched a lot about such tools (v2ray,brook,shadowsocks,...) but all of them was written in golang, except trojan which was written in c++
I want to make an android VPN application and the size of the application is important for me, so I successfully built trojan for android and the zipped size reach about 1.5M, everything seems okay, but in my country, IP blocking is very active, so I decided to transfer trojan traffic through CDN by using a WebSocket tunnel (I found wstunnel [haskell] but the size is the matter!)

or can you add support for UDP in your project, like trojan or v2ray which encapsulation UDP traffic over TCP stream

**Comment by ninetymiles** [comment]
For the size issue
shadowsocks-libev was written by C, and the binary size is 3xx kB, I was used it on my Netgear WNDR3700 as a transparent proxy before, and the original shadowsocks was written by python indeed.

my project write in java, the runtime env is not small at all. I run in on a RaspberryPi4B as socks proxy and use a GCP micro instance as websocket server.

For the UDP support, it is included in the socks5 protocol, the support in on going, I will try add it in 1.5.x

**Comment by mokhtarabadi** [comment]
because I want to develop a VPN for android so the java runtime isn't my problem (android have JVM internally), I want to reduce the size of the final android application (APK), I checked shadowsocks and I found that doesn't support UDP over TCP or didn't support WebSocket without a plugin.

the best thing currently I found is trojan-gfw which was written in c++ and compiled size is about 1M for android arm device, but my problem is IP blocking, I live in Iran, and Iran have another great firewall like china, and can block IP very soon if deep packet inspection find unusual traffic, so I decided to use CDN like Cloudflare to bypass IP blocking, for using CDN I need to pass trojan traffic through WebSocket

how many times do think needed to develop UDP support?

**Comment by mokhtarabadi** [comment]
any news?

**Comment by ninetymiles** [comment]
local socks proxy already can support bind/udp associate, working on forward udp between websocket agent and local socks agent.
