### ISSUE TITLE
vps上，编译失败

### ISSUE THREAD

**Issue by luckypoem** [ninetymiles/wsl-socks#14]
hi.

root@racknerd-7b97d8:~/wsl-socks-by-ninetymiles# gradle package
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A new daemon was started but could not be connected to: pid=DaemonInfo{pid=29625, address=[230742ca-6ca7-44e2-bff5-7ae7deb32723 port:36587, addresses:[/127.0.0.1]], state=Busy, lastBusy=1654088335955, context=DefaultDaemonContext[uid=f701508b-543f-465f-b472-eef3be69d21c,javaHome=/root/jdk-8u92-linux-x64/jdk1.8.0_92,daemonRegistryDir=/root/.gradle/daemon,pid=29625,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]}, address= [230742ca-6ca7-44e2-bff5-7ae7deb32723 port:36587, addresses:[/127.0.0.1]]. See https://docs.gradle.org/7.4.2/userguide/troubleshooting.html#network_connection for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
root@racknerd-7b97d8:~/wsl-socks-by-ninetymiles#

怎么解决？谢谢回复

**Comment by ninetymiles** [comment]
看起来是你本地安装的gradle daemon启动问题，请用IDEA打开工程，让IDEA来正确调用gradle，或者手动用内嵌的gradlew
